name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push API Gateway
      - name: Build and push api-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./server/api-gateway
          push: true
          tags: huuluan2004/cheaptrip-api-gateway:latest

      # Build & push Auth Service
      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./server/auth-service
          push: true
          tags: huuluan2004/cheaptrip-auth-service:latest

      # Build & push Booking Service
      - name: Build and push booking-service
        uses: docker/build-push-action@v5
        with:
          context: ./server/booking-service
          push: true
          tags: huuluan2004/cheaptrip-booking-service:latest

      # Build & push Discounts Service
      - name: Build and push discounts-service
        uses: docker/build-push-action@v5
        with:
          context: ./server/discounts-service
          push: true
          tags: huuluan2004/cheaptrip-discounts-service:latest

      # Build & push Tours Service
      - name: Build and push tours-service
        uses: docker/build-push-action@v5
        with:
          context: ./server/tours-service
          push: true
          tags: huuluan2004/cheaptrip-tours-service:latest

      # Build & push Frontend (nếu muốn)
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./client/cheaptripfe
          push: true
          tags: huuluan2004/cheaptrip-frontend:latest 